# Generated by Django 3.2.2 on 2021-09-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Ym9vayUyMHBlbnxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&w=1000&q=80', max_length=500),
        ),
    ]
